#! /bin/bash

# Usage:
# 	./build <binary>
#
# E.g.:
#   ./build main
#   ./build fastlcd

# prereqs:
#     rustup target add thumbv7em-none-eabihf
#     rustup component add llvm-tools-preview
#     cargo install uf2conv cargo-binutils

set -e

mv -f *.uf2 *.bin /tmp
cargo build --release --bin $1
cargo objcopy --release --bin $1 -- -O binary $1.bin
uf2conv $1.bin --base 0x4000 --output $1.uf2
mv -f $1.bin /tmp