[package]
name = "pygamer-playground"
version = "0.1.0"
authors = [ "Arne Vansteenkiste <barnex@gmail.com>" ]
edition = "2021"

[dependencies]
pygamer = { git = "https://github.com/atsamd-rs/atsamd" }
embedded-graphics = "0.7.1"
panic-halt = "0.2"
tinybmp = "0.3.1"


[target.thumbv7em-none-eabihf]
runner = "hf2 elf"
#runner = 'probe-run --chip ATSAMD51J19A'

[build]
target = "thumbv7em-none-eabihf"
rustflags = [

   # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
   # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
   "-C", "link-arg=--nmagic",

   "-C", "link-arg=-Tlink.x",
]


## [dependencies]
## cortex-m = "0.7"
## st7735-lcd = "0.8.1"
## ws2812-timer-delay = "0.3"
## 
## [dependencies.cortex-m-rt]
## version = "0.7"
## optional = true
## 
## [dependencies.atsamd-hal]
## version = "0.14"
## default-features = false
## 
## [dependencies.micromath]
## version = "0.5.1"
## optional = true
## 
## [dependencies.embedded-sdmmc]
## version = "0.3.0"
## optional = true
## 
## [dependencies.usb-device]
## version = "0.2"
## optional = true
## 
## [dev-dependencies]
## usbd-serial = "0.1"
## panic-halt = "0.2"
## embedded-graphics = "0.7.1"
## smart-leds = "0.3"
## ws2812-spi = { version = "0.4.0", features = ["mosi_idle_high"] }
## lis3dh = "0.1.0"
## cortex-m-rtic = "1.0"
## tinybmp = "0.3.1"
## 
## [features]
## # ask the HAL to enable atsamd51j support
## default = ["rt", "atsamd-hal/samd51j", "atsamd-hal/samd51", "unproven"]
## rt = ["cortex-m-rt", "atsamd-hal/samd51j-rt"]
## unproven = ["atsamd-hal/unproven"]
## usb = ["atsamd-hal/usb", "usb-device"]
## sd-card = ["embedded-sdmmc"]
## math = ["micromath"]
## panic_led = []
## 
## [profile.dev]
## # opt-level = 2 # uncomment for neopixel functionality during debug
## incremental = false
## debug = true
## lto = "thin" # thin for debug speed
## 
## [profile.release]
## lto = "fat"
## opt-level = 's'
## 
## # for cargo flash
## [package.metadata]
## chip = "ATSAMD51J19A"
## 
## 