[package]
name = "pygamer-playground"
version = "0.1.0"
authors = ["Arne Vansteenkiste <barnex@gmail.com>"]
edition = "2021"

[dependencies]
pygamer = { git = "https://github.com/atsamd-rs/atsamd" }
embedded-graphics = "0.7.1"
panic-halt = "0.2"
tinybmp = "0.3.1"
st7735-lcd = "0.8.1"
heapless = "0.7"
